env: "local" # local, dev, prod
token_ttl: 1h
#storage_path: "postgresql://m.savushkin@localhost:5432/auth_db?sslmode=disable"
grpc:
  port: 50051
  timeout: 4s
  idle_timeout: 60s
storage:
  db_type: "postgres"
  db_ssl: "disable"
  db_host: "localhost"
  db_port: 5432
  db_name: "auth_db"
  db_user: "m.savushkin"
  db_pass: "auth_user_local_pass"
migration_source_file_path: "file:./migrations"
